### ISSUE TITLE
Use GitHub Actions Rather than Travis

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-java#46]
For various reasons, we should use GitHub actions for CI rather than Travis:

## Expected

- Use GitHub Actions
- No Travis config: https://github.com/GoogleCloudPlatform/functions-framework-java/blob/master/.travis.yml

---

Here's an example GitHub Action workflow we can use:
https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

Maybe something like this:

```yaml
name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: (cd functions-framework-api/ && mvn install)
      - name: Test
        run: (cd invoker/ && mvn test)
```
